from .rest_plugin import default_rest_call, make_rest_call, augment_rest_call
from .sql_plugin import default_sql_call, make_sql_call, augment_sql_call
from .remote_cmd_plugin import default_remote_cmd_call, make_remote_cmd_call, augment_remote_cmd_call
from .local_cmd_plugin import default_local_cmd_call, make_local_cmd_call, augment_local_cmd_call
from .copy_remote_files_plugin import default_copy_remote_files_call, make_copy_remote_files_call, augment_copy_remote_files_call